# Generated by Django 3.2.8 on 2021-11-04 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.BooleanField(default=False)),
                ('refnum', models.CharField(max_length=13)),
                ('amount', models.IntegerField()),
                ('term_months', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=13)),
                ('age', models.IntegerField(default=18)),
                ('income', models.IntegerField(default=3000)),
                ('num_unsecured_l_term_all', models.IntegerField(default=1)),
                ('num_loan_payments_missed', models.IntegerField(default=0)),
                ('num_debit_orders_bounced', models.IntegerField(default=3)),
                ('wknd_shopper_flag', models.BooleanField(default=False)),
                ('salary_indicator', models.BooleanField(default=True)),
                ('num_credit_transactions', models.IntegerField(default=12)),
                ('house_credit_score', models.IntegerField(default=0)),
                ('num_properties_owned', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
